export class CustomerService{
  getCustomerList() {
      // Assume this data is coming from backend
      var customerList = [
        {fullName: 'Ajay', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Vijay', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'Ketan', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Sai', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'Raj', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Mohit', designation: 'Team Lead', salary: 100000},
        {fullName: 'Prasad', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Amit', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Pravin', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Shiva', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'Amol', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'Jitendra', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Navin', designation: 'Software Developer', salary: 50000},
        {fullName: 'Rushikesh', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Rohit', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Mayur', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'Abhijeet', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Akshay', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Virat', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Santosh', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Ganesh', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Shrikant', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Piyush', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Anand', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Pradip', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Vedant', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'Kiran', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'Sandip', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
        {fullName: 'John', designation: 'QA', salary: 40000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Mark', designation: 'Business Analyst', salary: 60000},
        {fullName: 'David', designation: 'Team Lead', salary: 100000},
        {fullName: 'Sam', designation: 'Software Developer', salary: 50000},
     
      ]




      return customerList;
    }
}

export interface Customer{
  fullName: string;
  designation: string;
  salary: number;
}
